version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.4.0
    volumes:
      - ./etc:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.1.5
    # We start the container using the same userid as you have locally for permissioning.
    user: ${UID}:${GID}
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana-data:/var/lib/grafana
    env_file:
      - ./etc/grafana-environment
    depends_on:
      - prometheus

  postgres:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: nutrack

  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.5.1
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:psql@postgres:5432/nutrack?sslmode=disable"

  # nginx:
  #   image: nginx:1.17.3-alpine
  #   restart: always
  #   ports:
  #     - 80:80

  # nutrack:
  #   image: clojure:openjdk-8-tools-deps
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:8080

  # build the server as a docker image - production edition
  # nutrack:
  #   build: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:8080
