version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.4.0
    volumes:
      - ./etc:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.1.5
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana-data:/var/lib/grafana
    env_file:
      - ./etc/grafana-environment
    depends_on:
      - prometheus

  # TODO: Potentially use this when you have a Dockerfile setup
  # app:
  #   build: .
  #   ports:
  #     - 8080:8080

