version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.4.0
    volumes:
      - ./etc:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.1.5
    # We start the container using the same userid as you have locally for permissioning.
    user: ${UID}:${GID}
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana-data:/var/lib/grafana
    env_file:
      - ./etc/grafana-environment
    depends_on:
      - prometheus

  nutrack:
    build: .
    ports:
      - 8080:8080

